-- FORTH WARS — esquema y seguridad
-- Ejecuta TODO este archivo en Supabase > SQL Editor.
-- Luego crea manualmente TU usuario administrador en Authentication > Users.

create table if not exists public.clan_settings (
  id int primary key default 1 check (id = 1),
  level int not null default 1,
  league text not null default 'Sin liga',
  streak int not null default 0,
  member_count int not null default 0,
  war_wins int not null default 0,
  war_losses int not null default 0,
  war_draws int not null default 0,
  war_best_streak int not null default 0,
  war_total int not null default 0,
  player_of_month uuid,
  highest_rank_player uuid,
  updated_at timestamptz not null default now()
);

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  town_hall int not null default 17,
  clan_role text not null default 'Miembro',
  stars int not null default 0,
  donations int not null default 0,
  medals int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prizes (
  id bigint generated by default as identity primary key,
  title text not null,
  winner text,
  reward text,
  month text,
  created_at timestamptz not null default now()
);

insert into public.clan_settings (id) values (1) on conflict (id) do nothing;

-- RLS: cualquiera puede leer los datos públicos.
alter table public.clan_settings enable row level security;
alter table public.members enable row level security;
alter table public.prizes enable row level security;

drop policy if exists "public read clan" on public.clan_settings;
create policy "public read clan" on public.clan_settings for select using (true);

drop policy if exists "public read members" on public.members;
create policy "public read members" on public.members for select using (true);

drop policy if exists "public read prizes" on public.prizes;
create policy "public read prizes" on public.prizes for select using (true);

-- SOLO usuarios autenticados pueden escribir.
-- Para una sola cuenta admin, usa la protección adicional del dashboard:
-- Authentication > Users > crea únicamente la cuenta que vaya a administrar.
drop policy if exists "authenticated update clan" on public.clan_settings;
create policy "authenticated update clan" on public.clan_settings for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists "authenticated insert members" on public.members;
create policy "authenticated insert members" on public.members for insert to authenticated with check (auth.uid() is not null);

drop policy if exists "authenticated update members" on public.members;
create policy "authenticated update members" on public.members for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists "authenticated delete members" on public.members;
create policy "authenticated delete members" on public.members for delete to authenticated using (auth.uid() is not null);

drop policy if exists "authenticated insert prizes" on public.prizes;
create policy "authenticated insert prizes" on public.prizes for insert to authenticated with check (auth.uid() is not null);

drop policy if exists "authenticated update prizes" on public.prizes;
create policy "authenticated update prizes" on public.prizes for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists "authenticated delete prizes" on public.prizes;
create policy "authenticated delete prizes" on public.prizes for delete to authenticated using (auth.uid() is not null);

-- Realtime
alter table public.clan_settings replica identity full;
alter table public.members replica identity full;
alter table public.prizes replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.clan_settings;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.members;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.prizes;
exception when duplicate_object then null;
end $$;

-- Actualización automática de updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists members_updated_at on public.members;
create trigger members_updated_at before update on public.members
for each row execute function public.set_updated_at();

drop trigger if exists clan_updated_at on public.clan_settings;
create trigger clan_updated_at before update on public.clan_settings
for each row execute function public.set_updated_at();
